// Generated by CoffeeScript 1.12.0
var Continuous;

Continuous = (function() {
  function Continuous(videoPlayer, videos1, autoRepeat, callback1) {
    this.videoPlayer = videoPlayer;
    this.videos = videos1 != null ? videos1 : [];
    this.autoRepeat = autoRepeat != null ? autoRepeat : false;
    this.callback = callback1;
    this.init_(videos, this.callback);
  }

  Continuous.prototype.init_ = function(videos, callback) {
    this.videoPlayer.setAttribute("src", videos[0]);
    this.videoPlayer.setAttribute("video_index", 0);
    this.videoPlayer.onended = (function(_this) {
      return function(e) {
        var index;
        index = parseInt(_this.videoPlayer.getAttribute("video_index"));
        index = index + 1;
        if (index < videos.length) {
          return _this.play_(index);
        } else if (index === videos.length && _this.autoRepeat) {
          return _this.play_(0);
        }
      };
    })(this);
    return this;
  };

  Continuous.prototype.play_ = function(index) {
    this.videoPlayer.setAttribute("video_index", index);
    this.videoPlayer.setAttribute("src", this.videos[index]);
    this.videoPlayer.play();
    if (this.callback) {
      this.callback(index, videos[index]);
    }
    return this;
  };

  Continuous.prototype.play = function(index) {
    return this.play_(index);
  };

  Continuous.prototype.playAfterReset = function() {
    return this.play_(0);
  };

  return Continuous;

})();
